/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package TP-Final-0.1.0.0 */
#ifndef VERSION_TP_Final
#define VERSION_TP_Final "0.1.0.0"
#endif /* VERSION_TP_Final */
#ifndef MIN_VERSION_TP_Final
#define MIN_VERSION_TP_Final(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_TP_Final */

/* package array-0.5.4.0 */
#ifndef VERSION_array
#define VERSION_array "0.5.4.0"
#endif /* VERSION_array */
#ifndef MIN_VERSION_array
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_array */

/* package base-4.14.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* tool alex-3.2.4 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.2.4"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */

/* tool gcc-9 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "9"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool happy-1.19.11 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.19.11"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 11)
#endif /* MIN_TOOL_VERSION_happy */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */

/* tool runghc-8.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.34 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.34"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  34 || \
  (major1) == 2 && (major2) == 34 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "TP-Final-0.1.0.0-LVuh7knrrW77JwIO9hNNXG"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "TP-Final-0.1.0.0-LVuh7knrrW77JwIO9hNNXG"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
